version: "3.9"

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
  redisdata:

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    image: mylaravel/php84-app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    env_file:
      - .env
    depends_on:
      - pg
      - redis
    networks:
      - laravel

  web:
    image: nginx:1.26-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
    depends_on:
      - app
    networks:
      - laravel
    command: ["/bin/sh", "-c", "rm -f /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]

  pg:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - laravel
